import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faArrowLeft,
  faArrowRight,
  faBars,
  faBell,
  faBookmark,
  faBug,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCode,
  faCog,
  faColumns,
  faComment,
  faCopy,
  faDatabase,
  faDownload,
  faEdit,
  faEnvelope,
  faExclamationTriangle,
  faExternalLinkAlt,
  faEye,
  faEyeSlash,
  faFile,
  faFileAlt,
  faFilePdf,
  faFilter,
  faHeart,
  faHome,
  faImage,
  faInfo,
  faLink,
  faList,
  faMinus,
  faMoon,
  faMusic,
  faPalette,
  faPhone,
  faPlus,
  faPrint,
  faQuestionCircle,
  faSave,
  faSearch,
  faServer,
  faShare,
  faSortDown,
  faSortUp,
  faSpinner,
  faStar,
  faSun,
  faTable,
  faTerminal,
  faTh,
  faTimes,
  faTrash,
  faUpload,
  faUser,
  faVideo,
} from "@fortawesome/free-solid-svg-icons";
import {
  faBookmark as farBookmark,
  faComment as farComment,
  faEnvelope as farEnvelope,
  faFile as farFile,
  faHeart as farHeart,
  faImage as farImage,
  faStar as farStar,
  faUser as farUser,
} from "@fortawesome/free-regular-svg-icons";
import {
  faApple,
  faFacebook,
  faGithub,
  faGoogle,
  faInstagram,
  faLinkedin,
  faMicrosoft,
  faNodeJs,
  faReact,
  faTwitter,
} from "@fortawesome/free-brands-svg-icons";
library.add(
  faBars,
  faTimes,
  faChevronDown,
  faChevronUp,
  faChevronLeft,
  faChevronRight,
  faArrowLeft,
  faArrowRight,
  faHome,
  faUser,
  faCog,
  faSearch,
  faFilter,
  faSun,
  faMoon,
  faEye,
  faEyeSlash,
  faPalette,
  faPlus,
  faMinus,
  faEdit,
  faTrash,
  faSave,
  faDownload,
  faUpload,
  faCopy,
  faShare,
  faPrint,
  faCheck,
  faTimes,
  faExclamationTriangle,
  faInfo,
  faQuestionCircle,
  faSpinner,
  faEnvelope,
  faPhone,
  faComment,
  faBell,
  faImage,
  faVideo,
  faMusic,
  faFile,
  faFileAlt,
  faFilePdf,
  faExternalLinkAlt,
  faLink,
  faBookmark,
  faHeart,
  faStar,
  faTh,
  faList,
  faTable,
  faColumns,
  faSortUp,
  faSortDown,
  faCode,
  faTerminal,
  faBug,
  faDatabase,
  faServer,
  farUser,
  farHeart,
  farStar,
  farBookmark,
  farComment,
  farEnvelope,
  farFile,
  farImage,
  faGithub,
  faTwitter,
  faLinkedin,
  faReact,
  faNodeJs,
  faGoogle,
  faMicrosoft,
  faApple,
  faFacebook,
  faInstagram,
  faFacebook,
  faTwitter
);
export const ICONS = {
  BARS: "bars",
  TIMES: "times",
  CHEVRON_DOWN: "chevron-down",
  CHEVRON_UP: "chevron-up",
  CHEVRON_LEFT: "chevron-left",
  CHEVRON_RIGHT: "chevron-right",
  ARROW_LEFT: "arrow-left",
  ARROW_RIGHT: "arrow-right",
  HOME: "home",
  USER: "user",
  COG: "cog",
  SEARCH: "search",
  FILTER: "filter",
  SUN: "sun",
  MOON: "moon",
  EYE: "eye",
  EYE_SLASH: "eye-slash",
  PALETTE: "palette",
  PLUS: "plus",
  MINUS: "minus",
  EDIT: "edit",
  TRASH: "trash",
  SAVE: "save",
  DOWNLOAD: "download",
  UPLOAD: "upload",
  COPY: "copy",
  SHARE: "share",
  PRINT: "print",
  CHECK: "check",
  EXCLAMATION_TRIANGLE: "exclamation-triangle",
  INFO: "info",
  QUESTION_CIRCLE: "question-circle",
  SPINNER: "spinner",
  ENVELOPE: "envelope",
  PHONE: "phone",
  COMMENT: "comment",
  BELL: "bell",
  IMAGE: "image",
  VIDEO: "video",
  MUSIC: "music",
  FILE: "file",
  FILE_ALT: "file-alt",
  FILE_PDF: "file-pdf",
  EXTERNAL_LINK: "external-link-alt",
  LINK: "link",
  BOOKMARK: "bookmark",
  HEART: "heart",
  STAR: "star",
  TH: "th",
  LIST: "list",
  TABLE: "table",
  COLUMNS: "columns",
  SORT_UP: "sort-up",
  SORT_DOWN: "sort-down",
  CODE: "code",
  TERMINAL: "terminal",
  BUG: "bug",
  DATABASE: "database",
  SERVER: "server",
  GITHUB: ["fab", "github"],
  TWITTER: ["fab", "twitter"],
  LINKEDIN: ["fab", "linkedin"],
  REACT: ["fab", "react"],
  NODEJS: ["fab", "node-js"],
  GOOGLE: ["fab", "google"],
  MICROSOFT: ["fab", "microsoft"],
  APPLE: ["fab", "apple"],
  FACEBOOK: ["fab", "facebook"],
  INSTAGRAM: ["fab", "instagram"],
} as const;
export enum IconStyle {
  SOLID = "fas",
  REGULAR = "far",
  BRANDS = "fab",
}
export type IconName = (typeof ICONS)[keyof typeof ICONS];
